const config = {
    INSTAGRAM_ACCESS_TOKEN: 'IGQVJYemo3eU5Pd2dfbndtQVhnWnIyZAk16NUdaTXgzZA1JUZA21XODNDV2RXNGpWZA01wVDVESnJTT0dPTGlCbm84ZAGg5LVI2cEhhRW5OUUdqRGR5UV9WWnFGckdqc05NenRla2FUdnVMZAXJHdHg3aFpVdAZDZD'
  };
  
  module.exports = config;